### ISSUE TITLE
trollius

### ISSUE THREAD

**Issue by KirstensGitHub** [ContextLab/Dartmouth-OpenBCI-Hackathon#2]
the streaming code requires users to have trollius (a quick pip install)
should we add this to the install.sh ?
@jeremymanning

**Comment by jeremymanning** [comment]
yes, we should add this (to all branches-- add to master, then pull master into each branch).  good thinking!

**Comment by KirstensGitHub** [comment]
awesome, thanks! There actually were one or two other items also missing from the install.sh (really obvious ones that most people should have, I think; we tested the install.sh on my new laptop though and needed to do a few additional installs). 

I think @andrewheusser added the additionally needed packages as part of the hypertools submodule requirements, but he'll have to verify how that works.

for now, I've removed trollius and made the code way more clean/simple, but we may want to add it back sometime in the future (maybe helpful if we livestream multiple subjects at once) in which case i'll add it to the install.sh

**Comment by jeremymanning** [comment]
ok!  closing issue...
